import { CartPage } from "../screen/CartPage"

export {Home} from "../screen/home/Home"
export {Layout} from "../components/common/Layout"
export {Hero} from "../components/hero/Hero"
export {InstagramPost} from "../components/hero/InstagramPost"
export {Product} from "../screen/product/Product"
export {ProductCard} from "../components/product/ProductCard"
export {ShippingInfo} from "../components/product/ShippingInfo"
export {Banner} from "../components/product/Banner"
export {ProductSlide} from "../components/product/ProductSlide"
export {Testimonials} from "../components/hero/Testimonials"
export {Shop} from "../../src/screen/shop/Shop"
export {ProductDetails} from "../screen/product/ProductDeatils"
